# 头部菜单
menu:
  Home: /
  Archives: /archives
  Reading: /categories/Read/
  GitHub: https://github.com/xuyuri
  RSS: /atom.xml
  About:  /about  

# Content
excerpt_link: Read More 	#摘要链接文字
fancybox: true 				#是否开启fancybox

# 侧边栏
sidebar: bottom  			#侧边栏显示位置
widgets: 					#侧边栏窗口部件
- category 					#分类
- tag 						#标签
- tagcloud 					#标签云
- archive 					#文章归档
- recent_posts 				#最近发布的文章
# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive
# widget behavior
archive_type: 'yearly' 	#按年存档，按月是monthly
show_count: false

# Miscellaneous
baidu_tongji: true 			#百度统计
#tencent_tongji: true 		#腾讯统计
google_analytics: 			#google统计-默认
favicon: /favicon.ico 		#favicon
twitter:
google_plus:
fb_admins:
fb_app_id:
